# Generated by Django 5.0.10 on 2024-12-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0002_river_riversection_river'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='osm_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='riversection',
            name='osm_way_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
