services:
  docs:
    image: closest_river_local_docs
    container_name: closest_river_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./closest_river:/app/closest_river:z
    ports:
      - '9000:9000'
    command: /start-docs
