volumes:
  production_postgres_data_backups: {}
  production_traefik: {}
  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: closest_river_production_django
    volumes:
      - /mnt/Data/closest_river/django_media:/app/closest_river/media:rw
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - 5000:5000

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: closest_river_production_postgres
    volumes:
      - /mnt/Data/closest_river/postgres:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    image: closest_river_production_celeryworker
    command: /start-celeryworker
    ports: []

  celerybeat:
    <<: *django
    image: closest_river_production_celerybeat
    command: /start-celerybeat
    ports: []

  flower:
    <<: *django
    image: closest_river_production_flower
    command: /start-flower
    ports:
      - 5555:5555

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: closest_river_production_nginx
    depends_on:
      - django
    volumes:
      - /mnt/Data/closest_river/django_media:/usr/share/nginx/media:ro
    ports:
      - 5001:80
